services:
  - type: web
    name: carbon-footprint-estimator
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.app:app
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
