services:
  - type: web
    name: carbon-footprint-estimator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
    region: oregon
    plan: free
    rootDir: backend
